### ISSUE TITLE
Sign up issue 

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/flex-originals#11]
**Describe the bug**
Sign up fails on the Sign Up page. This is critical because without signup developement is difficult.

**To Reproduce**
1. Clone project
2. execute `npm run dev`
3. go to sign up page and give credentials

**Screenshots**
![3](https://user-images.githubusercontent.com/40923324/70389362-91f1c400-19e4-11ea-8367-c5b2da0d7ec1.PNG)

**Desktop (please complete the following information):**
 - WSL on Windows 10
 - Chrome

**Comment by anuragteapot** [comment]
#12
