### ISSUE TITLE
Related to UI 

### ISSUE THREAD

**Issue by sk044** [NJACKWinterOfCode/flex-originals#14]
Not exactly a bug ,,, but something related to UI That doen't look good..
There is a lack of animation everywhere 
**To Reproduce**
1.It can be seen in the 4 dash menu over there in the home page.
2.The link which takes to the login page.

- OS: Ubuntu 19.10
 - Browser: chrome

**Comment by anuragteapot** [comment]
@sk044 I have updated the branch checkout `feature` branch.

**Comment by anuragteapot** [comment]
@sk044 here is a hosted version of application https://flexoriginals.ml/

**Comment by anuragteapot** [comment]
If it's not opening try to open with VPN. Some issue with IIT Patna wifi.

**Comment by sk044** [comment]
I think its not there in the hosted version maybe....
