### ISSUE TITLE
Equalizer can be added

### ISSUE THREAD

**Issue by sk044** [NJACKWinterOfCode/flex-originals#15]
Equalizer can be added in in it for better experience.

**Comment by anuragteapot** [comment]
I don't have any idea for now. But, If you can then it's great.  :)

**Comment by sk044** [comment]
Okay I am working on it....

**Comment by anuragteapot** [comment]
@sk044 You can work on other issues this is not a very necessary feature. This will take time and the probability  of success is very less.

**Comment by sk044** [comment]
Okay sure :)
