### ISSUE TITLE
Needs to update readme

### ISSUE THREAD

**Issue by sgpritam** [NJACKWinterOfCode/flex-originals#7]
update the readme and add git contribution command

**Comment by sgpritam** [comment]
@Anu1601CS Please review

**Comment by anuragteapot** [comment]
> update the readme and add git contribution command

mean ? which types of command ?

**Comment by sgpritam** [comment]
git clone,git add and so on

**Comment by sgpritam** [comment]
which is helpful for beginner and explain with some image
@Anu1601CS

**Comment by anuragteapot** [comment]
Ok. You want to add or should I add?

**Comment by sgpritam** [comment]
I want to add

**Comment by anuragteapot** [comment]
Ok great.

**Comment by sgpritam** [comment]
Please label my issue @Anu1601CS

**Comment by sgpritam** [comment]
@Anu1601CS Please review
